interface StringKeyObject {
    [key: string]: any;
}

export const languages:StringKeyObject = {
    "EN-GB":"英語（イギリス英語）",
    "EN-US":"英語（アメリカ英語）",
    "PT-PT":"ポルトガル語（ポルトガル）",
    "PT-BR":"ポルトガル語（ブラジル）",
    "BG":"ブルガリア語",
    "CS":"チェコ語",
    "DA":"デンマーク語",
    "DE":"ドイツ語",
    "EL":"ギリシャ語",
    "EN":"英語",
    "ES":"スペイン語",
    "ET":"エストニア語",
    "FI":"フィンランド語",
    "FR":"フランス語",
    "HU":"ハンガリー語",
    "IT":"イタリア語",
    "JA":"日本語",
    "LT":"リトアニア語",
    "LV":"ラトビア語",
    "NL":"オランダ語",
    "PL":"ポーランド語",
    "PT":"ポルトガル語",
    "RO":"ルーマニア語",
    "RU":"ロシア語",
    "SK":"スロバキア語",
    "SL":"スロヴェニア語",
    "SV":"スウェーデン語",
    "ZH":"中国語"
}

export const targetLangList = [
    "EN-GB",
    "EN-US",
    "PT-PT",
    "PT-BR",
    "BG",
    "CS",
    "DA",
    "DE",
    "EL",
    "EN",
    "ES",
    "ET",
    "FI",
    "FR",
    "HU",
    "IT",
    "JA",
    "LT",
    "LV",
    "NL",
    "PL",
    "PT",
    "RO",
    "RU",
    "SK",
    "SL",
    "SV",
    "ZH"
]
